// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZKh-0cTIfd63Jw7Z7PFn7FnuFx1hByk',
    appId: '1:261191708483:web:7a721488ec57b2c70009f6',
    messagingSenderId: '261191708483',
    projectId: 'my-task-manager-ed1b9',
    authDomain: 'my-task-manager-ed1b9.firebaseapp.com',
    storageBucket: 'my-task-manager-ed1b9.firebasestorage.app',
    measurementId: 'G-09FCWY0EB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGw6_H8HAlIisWBVs11Kzbr7hIZ3fg1w',
    appId: '1:261191708483:android:972ffa9895a09a5e0009f6',
    messagingSenderId: '261191708483',
    projectId: 'my-task-manager-ed1b9',
    storageBucket: 'my-task-manager-ed1b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3NkF7Ve0GoPZ3toRlGGI8iYQsb2ijn4M',
    appId: '1:261191708483:ios:c4adb8add3bc816c0009f6',
    messagingSenderId: '261191708483',
    projectId: 'my-task-manager-ed1b9',
    storageBucket: 'my-task-manager-ed1b9.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3NkF7Ve0GoPZ3toRlGGI8iYQsb2ijn4M',
    appId: '1:261191708483:ios:c4adb8add3bc816c0009f6',
    messagingSenderId: '261191708483',
    projectId: 'my-task-manager-ed1b9',
    storageBucket: 'my-task-manager-ed1b9.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaZKh-0cTIfd63Jw7Z7PFn7FnuFx1hByk',
    appId: '1:261191708483:web:8e6518835ba8a3ab0009f6',
    messagingSenderId: '261191708483',
    projectId: 'my-task-manager-ed1b9',
    authDomain: 'my-task-manager-ed1b9.firebaseapp.com',
    storageBucket: 'my-task-manager-ed1b9.firebasestorage.app',
    measurementId: 'G-2P81TX10P0',
  );
}
